### PR TITLE
Shared/Unique FFI unwrap

### PR DESCRIPTION
**Pull request by iduartgomez**
Split 'unwrap' method of FFI trait into shared (returns *const _) / owned (returns *mut _) methods, instead of just one method returning *mut _.

This allows applying ownership & mutability rules consistently across all the FFI bindings as long as the C definitions are correct (*const/*mut pointers where appropriate).

Will allow for implementation of unsafe sync/senc traits for certain types (like matrix) or use of smart pointers like Rc/RefCell etc.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Can you remove the merge commit please?

**Comment by GuillaumeGomez** [comment]
Why is the fix readme back? You should try to use the rebase strategy instead of the merge one. Allow to have way better git logs.

**Comment by iduartgomez** [comment]
yeah i was trying to rebase but screwed up, i can make a clean commit and delete this mess, sorry about that!

**Comment by GuillaumeGomez** [comment]
No problem, thanks a lot for all your work. It's really awesome!

**Comment by GuillaumeGomez** [comment]
If you don't know how to do it, you can take a look at this [blog post](https://blog.guillaume-gomez.fr/Git-tips/1/2).

**Comment by iduartgomez** [comment]
Yes that's what I was doing but I had to review changes in a lot of files due to the recent pull (the readme one) so it was a bit of a mess.

i made a new clean pull request based on the current HEAD so it's fixed anyway, no worries. i'll close this one down.

**Pull request closed without merging**
