### PR TITLE
changes to make it build on windows for gsl-1.16

### PR DESCRIPTION
**Pull request by qinwf**
Some changes to make it build on Win64

This one will remove some function. 

I do not know if it is a good idea to use casting on type on rng.rs. You can check it.

### CODE REVIEW

**Comment by qinwf** [comment]
I think we do not need to merge this for now, I only test it on Win64. The casting changes might not be needed on Win32.

**Comment by GuillaumeGomez** [comment]
Yes, and you have to specify the platform because it doesn't build on linux says travis.

**Comment by GuillaumeGomez** [comment]
@qinwf: Still not updated ? :(

**Comment by qinwf** [comment]
Sorry, I am not sure wether I could fix it for the moment, I think I should closed it for now.

**Comment by GuillaumeGomez** [comment]
Arf... That's too bad, it seemed interesting...

**Pull request closed without merging**
