### PR TITLE
Switch from deprecated std::old_io to std::io.

### PR DESCRIPTION
**Pull request by vberger**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
If didn't updated this because of an example, but mayb now it is a solved issue. Have you tested to compile examples ?

**Comment by vberger** [comment]
Oh, yeah, I'll update the examples as well.

**Comment by GuillaumeGomez** [comment]
I'll wait for that then.

**Comment by vberger** [comment]
(It is not finished, I have linking errors, I think I need to update my version of GSL. Which one are you using ?)

**Comment by vberger** [comment]
Alright, everything should be good now. `cargo test` builds all examples and there are no errors for me.

**Comment by GuillaumeGomez** [comment]
Oh ! An ICE ! I report it haha. Sorry but we'll have to wait before merging.

**Comment by GuillaumeGomez** [comment]
Like I said on the IRC, don't move file and update to the last version. I forgot to add the cargo file last time actually...

**Comment by GuillaumeGomez** [comment]
Thanks for your work !

**Pull request merged**
